# Generated by Django 4.1.3 on 2022-11-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=8)),
                ('product_description', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_stock', models.SmallIntegerField()),
                ('product_reserved', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_origin_url', models.CharField(max_length=255)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeder.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=100)),
                ('information_details', models.TextField(blank=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeder.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_url', models.CharField(max_length=255)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeder.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeder.products')),
            ],
        ),
    ]
