# Generated by Django 4.1.3 on 2022-11-08 08:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=8)),
                ('product_description', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_stock', models.SmallIntegerField(default=products.models.random_int)),
                ('product_reserved', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
