# Generated by Django 4.1.3 on 2022-11-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategories',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productsimages',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productsinformation',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productsurls',
            name='products',
        ),
        migrations.DeleteModel(
            name='InformationDetails',
        ),
        migrations.DeleteModel(
            name='ProductsCategories',
        ),
        migrations.DeleteModel(
            name='ProductsImages',
        ),
        migrations.DeleteModel(
            name='ProductsInformation',
        ),
        migrations.DeleteModel(
            name='ProductsURLs',
        ),
    ]
